//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRideApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public int servicioId { get; set; }
        public string detalle { get; set; }
        public System.DateTime fechaServicio { get; set; }
        public System.TimeSpan horaServicio { get; set; }
        public int empleadoId { get; set; }
        public int clienteId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
